# tests/singles/test_presentation_mode_gating.py
"""Player-mode sessions must not reach debug/GM commands.

Before this guard existed a brand-new level-1 character could run `level 5`,
`setgold 1000`, `sethealth 9999` and `teleport forest forest_edge` from the
real game server. Five debug commands declared an `operator.world.debug`
entitlement, but that gate is only defined when a server config generated by
the setup wizard is in use -- `server/config/server_config.json` does not exist
in the tree, and `EntitlementGuard.check()` returns *allow* for an undefined
gate. Everything else in the `debug` category declared no gate at all.

The fix gates the whole category on the session's `presentation_mode`, which is
the same switch that will decide whether engine internals are shown at all
(ROADMAP P1, docs/design/WORLD_DESIGN.md §2).

`test` mode is deliberately the default for a directly-constructed
HeadlessServer so the existing suite, the journey lab, and operator tooling keep
working unchanged; `player` is the default at the actual game entry points
(`JsonLineMudServer`, `JsonWebSocketMudServer`, `launch_content_set.py`).
"""

import re
import unittest

from engine.server.headless_server import HeadlessServer
from tests.fixtures import FANTASY_FRONTIER

MARKUP = re.compile(r"\[\[[^\]]*\]\]")

# One representative per debug module, plus the four the audit found reachable.
DEBUG_COMMANDS = [
    ("level 5", "state"),
    ("setgold 1000", "state"),
    ("sethealth 9999", "state"),
    ("teleport forest forest_edge", "world"),
    ("spawn wolf", "spawning"),
    ("campaign start bandit_rebellion", "quests"),
    ("settime day", "world"),
]


class TestPresentationModeGating(unittest.TestCase):

    def setUp(self):
        self._servers = []

    def tearDown(self):
        for server in self._servers:
            try:
                server.shutdown()
            except Exception:
                pass

    def _server(self, presentation_mode):
        server = HeadlessServer(
            db_path=":memory:",
            content_set_path=str(FANTASY_FRONTIER),
            default_presentation_mode=presentation_mode,
            save_directory=None,
        )
        self._servers.append(server)
        session = server.create_session(player_id="gating_%s" % presentation_mode)
        server.execute_command(session.session_id, "char create Gater")
        return server, session

    def _run(self, server, session, command):
        events = server.execute_command(session.session_id, command)
        return " ".join(
            MARKUP.sub("", str(e.get("payload", "")))
            for e in events
            if e.get("type") in {"text", "error"}
        ).strip()

    # -- the regression --------------------------------------------------

    def test_player_mode_denies_every_debug_command(self):
        server, session = self._server("player")
        for command, module in DEBUG_COMMANDS:
            with self.subTest(command=command, module=module):
                output = self._run(server, session, command)
                self.assertIn(
                    "permission", output.lower(),
                    "player-mode session reached debug command %r (got %r)"
                    % (command, output[:120]),
                )

    def test_player_mode_does_not_change_state(self):
        """A denied command must not have taken effect."""
        server, session = self._server("player")
        self._run(server, session, "setgold 1000")
        self._run(server, session, "level 5")
        player = server.get_player_for_session(session.session_id)
        self.assertEqual(player.runtime_state.gold, 0)
        self.assertEqual(player.runtime_state.progression.level, 1)
        self.assertEqual(self._run(server, session, "teleport forest forest_edge"),
                         "You do not have permission to use this command.")

    def test_player_mode_keeps_normal_gameplay_commands(self):
        """Gating the debug category must not gate the actual game."""
        server, session = self._server("player")
        for command in ("look", "status", "inventory", "journal", "recipes", "help"):
            with self.subTest(command=command):
                output = self._run(server, session, command)
                self.assertNotIn("permission", output.lower(),
                                 "player mode blocked an ordinary command: %s" % command)
                self.assertTrue(output, "ordinary command %s produced no output" % command)

    # -- test mode must be untouched -------------------------------------

    def test_test_mode_still_allows_debug_commands(self):
        server, session = self._server("test")
        self.assertIn("Gold set to 1000", self._run(server, session, "setgold 1000"))
        self.assertIn("level", self._run(server, session, "level 5").lower())
        self.assertIn("Teleported", self._run(server, session, "teleport forest forest_edge"))

    def test_session_can_override_the_server_default(self):
        server, _ = self._server("test")
        player_session = server.create_session(player_id="explicit_player", presentation_mode="player")
        server.execute_command(player_session.session_id, "char create Explicit")
        output = self._run(server, player_session, "setgold 1000")
        self.assertIn("permission", output.lower())

    def test_unknown_presentation_mode_falls_back_to_player(self):
        """An unrecognised mode must fail closed, not open."""
        server, _ = self._server("test")
        odd = server.create_session(player_id="odd_mode", presentation_mode="banana")
        self.assertEqual(odd.presentation_mode, "player")

    def test_server_default_mode_is_validated(self):
        server = HeadlessServer(
            db_path=":memory:",
            content_set_path=str(FANTASY_FRONTIER),
            default_presentation_mode="nonsense",
        )
        self._servers.append(server)
        self.assertEqual(server.default_presentation_mode, "test")
        session = server.create_session(player_id="validated")
        self.assertEqual(session.presentation_mode, "test")

    def test_default_session_mode_is_test_for_direct_construction(self):
        """Keeps the existing suite, journey lab and operator tooling working."""
        server = HeadlessServer(db_path=":memory:", content_set_path=str(FANTASY_FRONTIER))
        self._servers.append(server)
        self.assertEqual(server.default_presentation_mode, "test")
        self.assertEqual(server.create_session(player_id="default").presentation_mode, "test")


if __name__ == "__main__":
    unittest.main()
