# tests/singles/test_configuration_dialog_coverage.py
"""What the three configuration dialogs can author, checked against the schema.

`docs/plan/editor-coverage-ledger.md` records field coverage by hand. Two of its
rows are checkable mechanically, so they are checked here instead of asserted in
prose:

1. **The contract editor against the contract schema.** The dialog is generated by
   hand, so a field can be dropped from a builder without anything noticing -- the
   value then survives in the file but has no way to be authored, which is exactly
   the state the ledger calls *read-only* while the dialog's tab still looks
   complete. Every field of `CONTRACT_SCHEMAS` (and the file-level keys) must
   therefore be either written by the dialog or listed below with a reason.
2. **The combat vocabulary editor against the hazards the engine reads.** The
   dialog writes a fixed set of hazard keys; when a hazard grows a field the engine
   consumes, the dialog silently stops being able to author it.

The lists below are the *record*. A new uncovered field is a failure until someone
adds it here with a reason, and a listed field that becomes covered is also a
failure, so the record cannot rot in either direction.

Deliberately not checked: whether a written field is *read* by the engine. Several
are not (`item_families.label`, `attack_profiles.cooldown`), and that is a finding
for the ledger's dead-declaration section, not a defect in the dialog.
"""

import json
import re
import sys
import unittest
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[3]
SERVER_ROOT = REPOSITORY_ROOT / "server"
if str(SERVER_ROOT) not in sys.path:  # the suite runs with `server/` as its root
    sys.path.insert(0, str(SERVER_ROOT))

from engine.contracts.registry import CONTRACT_SCHEMAS, TOP_LEVEL_FIELDS  # noqa: E402

EDITOR_MODALS = REPOSITORY_ROOT / "mud-world-editor" / "scripts" / "ui" / "modals"
CONTRACT_DIALOG = EDITOR_MODALS / "ContractEditorDialog.gd"
COMBAT_DIALOG = EDITOR_MODALS / "CombatVocabularyDialog.gd"
RULESET_DIALOG = EDITOR_MODALS / "RulesetEditorDialog.gd"
RULESET_DRAFT = REPOSITORY_ROOT / "mud-world-editor" / "scripts" / "data" / "RulesetDraft.gd"
FANTASY = REPOSITORY_ROOT / "content_sets" / "fantasy_frontier"

# `_option(grid, "Target", ["self", "ally", ...], ...)` -- the option list is not a
# field path, so it must not be read as one.
ENUM_LITERALS = {"self", "ally", "enemy", "room", "item", "area"}

SECTION_BUILDERS = {
    "resources": ("_add_resource_row", ()),
    "item_families": ("_add_family_row", ()),
    "generation_profiles": ("_add_profile_row", ("_family_option",)),
    "attack_profiles": ("_add_attack_row", ()),
    "defense_profiles": ("_add_defense_row", ()),
    "effect_packets": ("_add_effect_row", ()),
    "abilities": ("_add_ability_row", ()),
    "work": ("_add_work_row", ()),
}

# Fields the dialog writes without the shared field constructors, so the source
# scan cannot see them: {section: {field: why}}.
HAND_BUILT = {
    "resources": {
        "regenerates": "hand-built CheckBox, ContractEditorDialog.gd:110-115",
    },
}

# Fields of the engine's schema no dialog field writes, and the reason each is
# acceptable. Emptying an entry means implementing it; adding one means recording
# why the dialog does not offer it.
UNCOVERED_CONTRACT_FIELDS = {
    ("item_families", "description"): (
        "read by nothing (ledger F); preserved on save, not authorable"
    ),
    ("item_families", "debug_only"): (
        "read by nothing; the template-level `properties.debug_only` is the live key"
    ),
    ("<file>", "schema_version"): "engine-owned version, not an authoring field",
    ("<file>", "label"): "file-level label, unread by the engine; preserved as authored",
    ("<file>", "description"): "file-level description, unread; preserved as authored",
}

# The ruleset keys the dialog can write. The first three are scalars; `world`
# and `combat` are written by `_put_path`, the rest through `RulesetDraft`
# setters. Anything else in `ruleset.json` is preserved byte-for-byte and
# cannot be authored.
RULESET_WRITABLE_KEYS = {
    "ruleset_id",
    "world_mode",
    "progression_model",
    "systems",
    "world",
    "factions",
    "status",
    "combat",
    "crafting",
    "skills",
    "npc_schedules",
    "advancement",
    "weather",
    "quest_generation",
    "economy",
    "locksmithing",
    "calendar",
    "spawning",
    "elites",
    "npc_naming",
    "player_defaults",
}

# Top-level keys of `combat/elements.json` the dialog does not write.
UNCOVERED_COMBAT_KEYS = {
    "elemental_opposites": "no editor control; the engine reads it for prose only",
    "flavor_text": "no editor control; read for hazard prose",
}

# Hazard fields the dialog builds by hand, so the scan cannot see them.
HAND_BUILT_HAZARD_FIELDS = {
    "flavor": "hand-built TextEdit, CombatVocabularyDialog.gd:57-64",
}

# Ruleset keys the dialog can write that no shipped set declares. `factions` is
# read by the engine (`world/factions.py`) and validated (`content_set.py:854-880`)
# but declared by none of the four sets -- so the "Custom Factions" panel authors a
# section with no shipped example to copy from. Recorded, not hidden.
RULESET_KEYS_NO_SET_DECLARES = {"factions"}


# --- source reading ---------------------------------------------------------


def function_body(source: str, name: str) -> str:
    """The body of `func name(...)`, up to the next top-level function."""
    body: list[str] = []
    inside = False
    for line in source.splitlines():
        if line.startswith("func %s(" % name):
            inside = True
            continue
        if inside and line.startswith("func "):
            break
        if inside:
            body.append(line)
    return "\n".join(body)


def calls(text: str, name: str):
    """The argument text of every `name(...)` call, with parens balanced."""
    for match in re.finditer(re.escape(name) + r"\(", text):
        depth = 1
        index = match.end()
        while index < len(text) and depth:
            if text[index] == "(":
                depth += 1
            elif text[index] == ")":
                depth -= 1
            index += 1
        yield text[match.end():index - 1]


def field_paths(source_text: str) -> set[str]:
    """Every field path handed to a field constructor in one function body."""
    paths: set[str] = set()
    for constructor in ("_field", "_number_field", "_option", "_text_area", "_hazard_field"):
        for span in calls(source_text, constructor):
            quoted = re.findall(r'"([^"]*)"', span)
            if quoted:
                paths.add(quoted[-1])
    for span in calls(source_text, "_add_tier_section"):
        paths |= set(re.findall(r'"([a-z_]+_tiers)"', span))
    return {path for path in paths if path not in ENUM_LITERALS}


def authored_fields(dialog_source: str, builder: str, helpers=()) -> set[str]:
    paths = field_paths(function_body(dialog_source, builder))
    for helper in helpers:
        paths |= field_paths(function_body(dialog_source, helper))
    return paths


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def ruleset_written_keys(dialog_source: str) -> set[str]:
    """The top-level `ruleset.json` keys `RulesetEditorDialog._save` can change.

    The scalars and the region-policy flags are both written through a
    `for pair in [[<control>, "<field>"], ...]` loop, and the two loops differ in
    how `_put_path` spells the key: the scalars pass `pair[1]` directly, the region
    flags concatenate a literal prefix. So the loop's literals are top-level keys
    only when the call that follows does not prefix them.
    """
    body = function_body(dialog_source, "_save")
    lines = body.splitlines()
    written: set[str] = set()
    pending: list[str] = []
    for line in lines:
        if "for pair in [" in line:
            pending = [
                match.group(1).split(".")[0]
                for match in re.finditer(r'\[[a-z_]+,\s*"([a-z_.]+)"\]', line)
            ]
            continue
        if "_put_path(" in line:
            literal = re.search(r'_put_path\(draft\.data,\s*"([a-z_.]+)"', line)
            if literal:
                written.add(literal.group(1).split(".")[0])
            else:
                written |= set(pending)
            pending = []
    for method in re.findall(r"draft\.(set_[a-z_]+)\(", body):
        keys = RULESET_SETTER_KEYS.get(method, "<unmapped %s>" % method)
        written |= set(keys) if isinstance(keys, tuple) else {keys}
    return written


# The top-level key each `RulesetDraft` setter writes. A setter missing here
# shows up as `<unmapped ...>` in the written set rather than being skipped.
RULESET_SETTER_KEYS = {
    "set_system_enabled": "systems",
    "set_faction_extras": "factions",
    "set_status_stats": "status",
    "set_salvage_rules": "crafting",
    "set_skill_stat_bonuses": "skills",
    "set_npc_schedules": "npc_schedules",
    "set_advancement": "advancement",
    "set_weather_descriptions": "weather",
    "set_weather_profiles": "weather",
    "set_quest_generation": "quest_generation",
    "set_world_rules": ("economy", "locksmithing", "calendar", "spawning", "elites", "npc_naming", "player_defaults"),
}


class TestTheContractDialogAuthorsEverySchemaField(unittest.TestCase):
    def setUp(self) -> None:
        self.source = read(CONTRACT_DIALOG)

    def test_every_contract_field_is_authorable_or_recorded(self) -> None:
        uncovered: dict[tuple[str, str], str] = {}
        for section, (builder, helpers) in SECTION_BUILDERS.items():
            # A nested path (`cost.resource`) covers the field it belongs to, so the
            # comparison is on the top-level segment the schema declares.
            covered = {
                path.split(".")[0]
                for path in authored_fields(self.source, builder, helpers)
            }
            covered |= set(HAND_BUILT.get(section, {}))
            for field in CONTRACT_SCHEMAS[section]:
                if field not in covered:
                    uncovered[(section, field)] = ""
        self.assertEqual(
            sorted(key for key in UNCOVERED_CONTRACT_FIELDS if key[0] != "<file>"),
            sorted(uncovered),
            "The contract dialog's field coverage changed. Implement the field or "
            "record why it is not offered in UNCOVERED_CONTRACT_FIELDS.",
        )

    def test_every_contract_section_has_a_builder(self) -> None:
        self.assertEqual(
            sorted(CONTRACT_SCHEMAS),
            sorted(SECTION_BUILDERS),
            "A contract section was added to the engine without a dialog tab, or a "
            "tab was renamed without this table following it.",
        )

    def test_the_file_level_fields_are_accounted_for(self) -> None:
        file_level = set(TOP_LEVEL_FIELDS) - set(CONTRACT_SCHEMAS) - {"stats"}
        recorded = {field for (section, field) in UNCOVERED_CONTRACT_FIELDS if section == "<file>"}
        self.assertEqual(
            sorted(file_level),
            sorted(recorded),
            "`world_contracts.json`'s file-level keys changed; the dialog shows none "
            "of them, so each needs a recorded reason.",
        )

    def test_stats_is_authorable_field_by_field(self) -> None:
        """`stats` is an object, not a list of entries, so it has its own page."""
        body = function_body(self.source, "_make_stats_page")
        self.assertIn("stats_order", body)
        self.assertIn("stats_short", body)
        self.assertIn("STAT_ROLES", body)
        self.assertEqual(
            sorted(TOP_LEVEL_FIELDS["stats"]["fields"]),
            sorted(("order", "short", "roles")),
            "The engine's stats shape changed; the Stats page must follow it.",
        )


class TestTheRulesetDialogWritesOnlyWhatItClaims(unittest.TestCase):
    def test_the_writable_ruleset_keys_are_exactly_the_recorded_set(self) -> None:
        written = ruleset_written_keys(read(RULESET_DIALOG))
        self.assertEqual(
            sorted(RULESET_WRITABLE_KEYS),
            sorted(written),
            "The ruleset editor's writable keys changed. Anything else in "
            "`ruleset.json` is preserved byte-for-byte, so widening this set means "
            "the ledger's ruleset table and this record must both move.",
        )

    def test_the_written_keys_exist_in_a_shipped_ruleset(self) -> None:
        declared: set[str] = set()
        for set_id in ("fantasy_frontier", "night_shift", "orbital_salvage", "modern_capsule"):
            path = REPOSITORY_ROOT / "content_sets" / set_id / "rules" / "ruleset.json"
            if path.is_file():
                declared |= set(json.loads(read(path)))
        self.assertEqual(
            sorted(RULESET_KEYS_NO_SET_DECLARES),
            sorted(RULESET_WRITABLE_KEYS - declared),
            "A ruleset section the editor can author is declared by no shipped set. "
            "That is recorded, not hidden: update RULESET_KEYS_NO_SET_DECLARES.",
        )


class TestTheCombatDialogAuthorsEveryHazardKey(unittest.TestCase):
    def setUp(self) -> None:
        self.source = read(COMBAT_DIALOG)
        self.elements = json.loads(read(FANTASY / "data" / "combat" / "elements.json"))

    def test_every_hazard_key_in_the_shipped_file_is_authorable(self) -> None:
        shipped: set[str] = set()
        for hazard in self.elements.get("hazards", {}).values():
            shipped |= set(hazard)
        authored = field_paths(function_body(self.source, "_add_hazard"))
        # `hazard_id` is the row's own control for the hazards map key, not a field
        # of the hazard record.
        authored.discard("hazard_id")
        authored |= set(HAND_BUILT_HAZARD_FIELDS)
        self.assertEqual(
            sorted(shipped),
            sorted(authored),
            "A hazard key the engine reads has no control, or the dialog writes a key "
            "the shipped hazards do not use.",
        )

    def test_the_top_level_keys_are_recorded(self) -> None:
        file_keys = set(self.elements) - {"hazards"} - {
            key for key in self.elements if key.startswith("_")
        }
        written = set(re.findall(r'draft\.data\["([a-z_]+)"\]', function_body(self.source, "_save")))
        recorded = written | set(UNCOVERED_COMBAT_KEYS)
        self.assertEqual(
            sorted(file_keys),
            sorted(recorded),
            "`elements.json`'s top-level keys changed. Add the control or record why "
            "it has none in UNCOVERED_COMBAT_KEYS.",
        )


class TestTheCoverageScanItself(unittest.TestCase):
    """The scan is a regex over GDScript, so it needs its own falsification."""

    def test_the_scan_reads_the_last_argument_not_the_label(self) -> None:
        snippet = '_field(grid, "ID", str(entry.get("id", "")), "id")\n'
        self.assertEqual({"id"}, field_paths(snippet))

    def test_the_scan_ignores_option_lists_that_look_like_paths(self) -> None:
        snippet = '_option(grid, "Target", ["self", "enemy"], "enemy", "target_type")\n'
        self.assertEqual({"target_type"}, field_paths(snippet))

    def test_the_scan_sees_a_hand_built_control_only_when_it_is_recorded(self) -> None:
        """A checkbox built by hand is invisible to the scan -- hence HAND_BUILT."""
        snippet = 'var regenerates := CheckBox.new()\nregenerates.text = "Regenerates"\n'
        self.assertEqual(set(), field_paths(snippet))
        self.assertIn("regenerates", HAND_BUILT["resources"])


if __name__ == "__main__":
    unittest.main()
