# scripts/data/QuestSchema.gd
#
# The engine's quest vocabulary, in one place, so the editor's quest surface
# writes what the engine reads.
#
# The old QuestInspector wrote `{id, description, type: "KILL", target, count,
# next}` while the engine reads `stage.objective.type` and routes only the types
# it knows (engine/server/content_set.py::_validate_quests,
# engine/core/quests/tracker.py, engine/core/quests/manager.py,
# engine/core/quest_generation/objectives.py). A stage authored that way passed
# content validation with zero errors and could never be completed. This file is
# the fix: one table of types and fields, with the engine location each entry
# comes from, so the next engine type is a one-line addition here rather than a
# guess in an inspector.
#
# Widget kinds: string, int, bool, item_id, npc_id, string_list, choices, json.
# `required` fields are the ones a validator or the tracker reads; `optional`
# ones are authored where content wants them. `runtime` fields are written by the
# engine while the quest runs -- shown read-only, never invented here.

class_name QuestSchema
extends RefCounted

const TYPES := {
	"kill": {
		"label": "Kill",
		"required": {"target_template_id": "npc_id"},
		"optional": {"target_name": "string", "required_quantity": "int", "require_elite": "bool"},
		"runtime": ["current_quantity"],
		"note": "Counts kills of that NPC template (tracker.check_kill_objectives).",
	},
	"group_kill": {
		"label": "Kill a group",
		"required": {},
		"optional": {"targets": "json", "targets_config": "json"},
		"runtime": [],
		"note": "`targets` is {template_id: {name, required}}; the generator authors `targets_config`.",
	},
	"fetch": {
		"label": "Fetch",
		"required": {"item_id": "item_id"},
		"optional": {"item_name": "string", "required_quantity": "int", "consume_item": "bool"},
		"runtime": ["current_quantity"],
		"note": "Handing the item over completes it; `consume_item` takes it (commands/interaction/npcs.py).",
	},
	"fetch_procedural": {
		"label": "Fetch (generated)",
		"required": {},
		"optional": {"item_name": "string", "required_quantity": "int"},
		"runtime": [],
		"note": "Generated by the quest generator; the item does not exist until the quest starts.",
	},
	"deliver": {
		"label": "Deliver",
		"required": {"item_template_id": "item_id"},
		"optional": {
			"item_to_deliver_name": "string",
			"recipient_template_id": "npc_id",
			"recipient_name": "string",
			"recipient_instance_id": "string",
			"crafted_only": "bool",
			"min_material_quality_score": "int",
		},
		"runtime": ["item_instance_id"],
		"note": "`crafted_only` refuses a bought one; `min_material_quality_score` is the rolled material grade (use_give.py).",
	},
	"deliver_multi": {
		"label": "Deliver to several",
		"required": {"item_template_id": "item_id", "recipients": "json"},
		"optional": {"item_to_deliver_name": "string", "required_quantity": "int"},
		"runtime": [],
		"note": "`recipients` is a list of at least two {template_id, name} entries (content_set.py).",
	},
	"scout": {
		"label": "Scout",
		"required": {"target_region": "string"},
		"optional": {"target_room_id": "string", "target_room_keywords": "string_list"},
		"runtime": [],
		"note": "Visiting the room (or any room matching a keyword) completes it (manager.py).",
	},
	"negotiate": {
		"label": "Negotiate",
		"required": {"target_npc_id": "npc_id", "choices": "choices"},
		"optional": {"approach": "string", "skill": "string", "difficulty": "int"},
		"runtime": [],
		"note": "A skill check decides which choice outcome applies; every outcome needs `next_stage` or `complete`.",
	},
	"dialogue_choice": {
		"label": "Dialogue choice",
		"required": {"choices": "choices"},
		"optional": {},
		"runtime": [],
		"note": "Same outcome shape as negotiate, with no check in front of it.",
	},
	"relationship": {
		"label": "Relationship",
		"required": {"target_npc_template_id": "npc_id", "required_score": "int"},
		"optional": {"npc_name": "string"},
		"runtime": [],
		"note": "Completes when that NPC's relationship score reaches `required_score` (tracker.py).",
	},
	"discover_n": {
		"label": "Discover N",
		"required": {"kind": "string", "required_count": "int"},
		"optional": {},
		"runtime": [],
		"note": "`kind` is an advancement-ledger entry kind; the count must be at least 1 (content_set.py).",
	},
	"craft_quality": {
		"label": "Craft at quality",
		"required": {"recipe_id": "string", "required_quality_id": "string"},
		"optional": {},
		"runtime": [],
		"note": "Both ids are validated against the recipe and its quality tiers (content_set.py).",
	},
	"gather_types": {
		"label": "Gather these",
		"required": {"required_item_ids": "string_list"},
		"optional": {},
		"runtime": ["gathered_item_ids"],
		"note": "Gathering each listed item once completes it (tracker.py).",
	},
	"clear_region": {
		"label": "Clear the instance",
		"required": {"target_template_id": "npc_id"},
		"optional": {},
		"runtime": [],
		"note": "Needs an instanced quest region: kills in the instance are counted (tracker.py).",
	},
	"escort": {
		"label": "Escort",
		"required": {"spawn_config": "json"},
		"optional": {},
		"runtime": ["target_npc_instance_id"],
		"note": "`spawn_config` is {template_id, name, region_id, room_id} (manager.py).",
	},
}

# Stage-level fields the engine reads, beyond the objective.
const STAGE_FIELDS := {
	"stage_index": "Position in the quest's stage list; the editor keeps these in order.",
	"description": "What the journal shows for this stage.",
	"objective": "The one thing this stage asks for.",
	"objectives_any": "Alternative routes: completing any one of them satisfies the stage.",
	"turn_in_id": "NPC template id to hand the finished quest to.",
	"completion_dialogue": "What the giver says when it is handed in.",
	"start_dialogue": "Said when the stage begins, where authored.",
	"spawn_on_entry": "Spawns an NPC when the player enters a matching room: {template_id, region_id, room_id, name_override?, behavior_type?}.",
	"spawn_on_start": "Spawns an NPC when the stage begins: {template_id, region_id, room_id, name_override?}.",
}

# Keys the engine writes while the quest runs. Never authored, never removed, and
# shown as read-only so an author can see the state a stage carries.
const RUNTIME_KEYS := ["current_quantity", "item_instance_id", "gathered_item_ids", "target_npc_instance_id", "_spawn_on_entry_triggered"]


static func type_ids() -> Array:
	var ids := TYPES.keys()
	ids.sort()
	return ids


static func has_type(type_id: String) -> bool:
	return TYPES.has(type_id)


static func entry(type_id: String) -> Dictionary:
	return TYPES.get(type_id, {})


static func label_for(type_id: String) -> String:
	var spec: Dictionary = TYPES.get(type_id, {})
	return str(spec.get("label", type_id if type_id != "" else "(no type)"))


static func note_for(type_id: String) -> String:
	return str(entry(type_id).get("note", "This type is not one the editor knows; the fields are shown as authored."))


# Fields an author may set for this type, in a stable order: required first.
static func authored_fields(type_id: String) -> Dictionary:
	var spec := entry(type_id)
	var fields := {}
	for key in spec.get("required", {}):
		fields[key] = spec["required"][key]
	for key in spec.get("optional", {}):
		fields[key] = spec["optional"][key]
	return fields


static func is_runtime_key(key: String) -> bool:
	return RUNTIME_KEYS.has(key)


# Keys present in `objective` that this table does not describe: shown, editable,
# and never dropped -- content may be ahead of the editor, and losing a field
# nobody modelled is how a working quest stops working.
static func extra_keys(objective: Dictionary) -> Array:
	var known := authored_fields(str(objective.get("type", "")))
	var extras: Array = []
	for key in objective:
		if key == "type" or known.has(key) or is_runtime_key(str(key)):
			continue
		extras.append(key)
	extras.sort()
	return extras
